"use client";

import { useEffect, useState } from "react";
import { API, CommandBar, EmptyState, InlineEdit, ListRail, PageHeader, Segmented, Shell, TaskRow } from "../components";

const views = [["open", "open"], ["today", "today"], ["week", "next 7 days"], ["overdue", "overdue"], ["all", "everything"]];

export default function Tasks() {
  const [lists, setLists] = useState([]); const [list, setList] = useState(""); const [view, setView] = useState("open"); const [tasks, setTasks] = useState([]); const [tags, setTags] = useState([]); const [tag, setTag] = useState(""); const [query, setQuery] = useState(""); const [editing, setEditing] = useState(null); const [moving, setMoving] = useState(null); const [parsed, setParsed] = useState(null); const [error, setError] = useState("");
  async function loadLists() { const response = await fetch(`${API}/tasks/lists/`); if (response.ok) setLists((await response.json()).lists); }
  async function loadTasks() { const params = new URLSearchParams({ view, list }); if (tag) params.set("tag", tag); const response = await fetch(`${API}/tasks/?${params}`); if (response.ok) setTasks((await response.json()).tasks); }
  async function loadTags() { const response = await fetch(`${API}/tasks/tags/?list=${encodeURIComponent(list)}`); if (response.ok) setTags((await response.json()).tags); }
  useEffect(() => { const initial = new URLSearchParams(window.location.search).get("list"); if (initial !== null) setList(initial); loadLists(); }, []);
  useEffect(() => { loadTasks(); loadTags(); }, [view, list, tag]);
  async function add(text) { setError(""); const response = await fetch(`${API}/tasks/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text, list }) }); if (!response.ok) { setError((await response.json()).error || "Could not add task"); return false; } setParsed((await response.json()).task); await Promise.all([loadTasks(), loadLists(), loadTags()]); return true; }
  async function toggle(task) { await fetch(`${API}/tasks/${task.id}/?list=${encodeURIComponent(list)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ done: !task.done }) }); loadTasks(); loadLists(); }
  async function remove(id) { await fetch(`${API}/tasks/${id}/?list=${encodeURIComponent(list)}`, { method: "DELETE" }); loadTasks(); loadLists(); }
  async function saveTask(values) { await fetch(`${API}/tasks/${editing.id}/?list=${encodeURIComponent(list)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); setEditing(null); loadTasks(); }
  async function moveTask(target) { if (!moving || target === list) return; await fetch(`${API}/tasks/move/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: [moving.id], source: list, target }) }); setMoving(null); await Promise.all([loadTasks(), loadLists()]); }
  async function search(event) { event.preventDefault(); if (!query.trim()) return loadTasks(); const response = await fetch(`${API}/tasks/find/?q=${encodeURIComponent(query)}&list=${encodeURIComponent(list)}`); if (response.ok) setTasks((await response.json()).tasks); }
  async function createList(name) { setLists(current => current.some(item => item.name === name) ? current : [...current, { name, label: `@${name}`, open_count: 0, total_count: 0 }]); setList(name); setTag(""); }
  return <Shell lists={lists}><PageHeader eyebrow={`todo / ${list ? `@${list}` : "default"}`} title="Tasks" detail="Your workbench for the things that need doing. Capture naturally; jasem keeps the structure in sync." action={<span className="mono">{tasks.length} showing</span>} /><CommandBar placeholder="try: review release next Friday, high priority, work" onSubmit={add} parsed={parsed} error={error} button="Add task" /><div className="tasks-layout"><ListRail lists={lists} selected={list} onSelect={name => { setList(name); setTag(""); }} onCreate={createList} /><section className="tasks-main"><form className="search-line" onSubmit={search}><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Find by title or tag" /><button aria-label="Search">⌕</button></form><Segmented items={views} value={view} onChange={setView} />{tags.length > 0 && <div className="tag-filter"><span>tags</span>{tags.map(item => <button className={tag === item.tag ? "active" : ""} key={item.tag} onClick={() => setTag(tag === item.tag ? "" : item.tag)}>#{item.tag} <b>{item.count}</b></button>)}</div>}{moving && <div className="move-strip"><span>move “{moving.title}” to</span>{lists.filter(item => item.name !== list).map(item => <button key={item.name} onClick={() => moveTask(item.name)}>{item.label}</button>)}<button className="cancel" onClick={() => setMoving(null)}>cancel</button></div>}{tasks.length ? tasks.map(task => <div key={task.id}>{editing?.id === task.id ? <InlineEdit fields={[{ key: "title", label: "task", value: task.title }, { key: "deadline", label: "deadline", value: task.deadline }, { key: "priority", label: "priority", value: task.priority }, { key: "tags", label: "tags", value: task.tags.join(" ") }]} onSave={saveTask} onCancel={() => setEditing(null)} /> : <TaskRow task={task} onToggle={toggle} onDelete={remove} onEdit={setEditing} onMove={setMoving} />}</div>) : <EmptyState title="Nothing in this view." detail="Capture the next thing above, or switch lists to find it." />}</section></div><div className="footer-note">{list ? `@${list}` : "default"} · changes write directly to ~/.jasem/tasks{list ? `-${list}` : ""}.md</div></Shell>;
}
