"use client";

import { useEffect, useState } from "react";
import { API, BarTrend, CommandBar, EmptyState, InlineEdit, PageHeader, Segmented, Shell, Stat } from "../components";

const periods = [["all", "all time"], ["today", "today"], ["week", "last 7 days"], ["month", "last 30 days"]];

export default function Spending() {
  const [period, setPeriod] = useState("all"); const [tag, setTag] = useState(""); const [records, setRecords] = useState([]); const [report, setReport] = useState(null); const [tags, setTags] = useState([]); const [parsed, setParsed] = useState(null); const [error, setError] = useState(""); const [editing, setEditing] = useState(null);
  async function load() { try { const [listResponse, reportResponse, tagResponse] = await Promise.all([fetch(`${API}/spending/?period=${period}${tag ? `&tag=${encodeURIComponent(tag)}` : ""}`), fetch(`${API}/spending/?report=1&period=week${tag ? `&tag=${encodeURIComponent(tag)}` : ""}`), fetch(`${API}/spending/tags/`)]); if (!listResponse.ok || !reportResponse.ok) throw new Error("Could not load spending"); const listData = await listResponse.json(); setRecords(listData.records); setReport(await reportResponse.json()); if (tagResponse.ok) setTags((await tagResponse.json()).tags); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); }, [period, tag]);
  async function add(text) { setError(""); const response = await fetch(`${API}/spending/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text }) }); if (!response.ok) { setError("Could not record spending"); return false; } setParsed((await response.json()).record); load(); return true; }
  async function edit(values) { await fetch(`${API}/spending/${editing.id}/`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); setEditing(null); load(); }
  async function remove(id) { await fetch(`${API}/spending/${id}/`, { method: "DELETE" }); load(); }
  return <Shell><PageHeader eyebrow={`acc / ${period}`} title="Spending" detail="Keep the number beside the reason. Jasem turns a sentence into a searchable money log." action={<span className="mono">{records.length} records</span>} /><CommandBar placeholder="try: 50k lunch with the team yesterday, food" onSubmit={add} parsed={parsed} error={error} button="Record spend" /><section className="section"><div className="section-head"><h2>Report</h2><span>jasem acc report</span></div>{report && <div className="stat-strip"><Stat value={report.total_amount.toLocaleString()} label="spent" accent="gold" /><Stat value={report.active_days} label="active days" /><Stat value={report.avg_per_active_day.toLocaleString()} label="avg / active day" /><div className="trend-block"><div className="trend-title"><span>timeline</span><b>{report.timeline_unit}</b></div><BarTrend values={report.timeline.map(item => item[1])} color="gold" /></div></div>}</section><section className="section"><div className="section-head"><h2>Log</h2><span>{period}{tag ? ` · #${tag}` : ""}</span></div><Segmented items={periods} value={period} onChange={setPeriod} />{tags.length > 0 && <div className="tag-filter"><span>tags</span>{tags.map(item => <button className={tag === item.tag ? "active" : ""} key={item.tag} onClick={() => setTag(tag === item.tag ? "" : item.tag)}>#{item.tag} <b>{item.count}</b></button>)}</div>}{records.length ? records.slice().reverse().map(record => editing?.id === record.id ? <InlineEdit key={record.id} fields={[{ key: "amount_text", label: "amount", value: record.amount_text }, { key: "title", label: "title", value: record.title }, { key: "description", label: "note", value: record.description }, { key: "date", label: "date", value: record.date }, { key: "tag", label: "tag", value: record.tag }]} onSave={edit} onCancel={() => setEditing(null)} /> : <div className="data-row" key={record.id}><span className="mono">#{record.id}<br />{record.date}</span><span>{record.title}<small>{record.description}</small></span><span className="amount">{record.amount_text}</span><span className="row-tag">#{record.tag} <button className="row-action" onClick={() => setEditing(record)}>edit</button><button className="row-action" onClick={() => remove(record.id)}>remove</button></span></div>) : <EmptyState title="No spending recorded here." detail="Record the next expense above." />}</section><div className="footer-note">amounts are stored exactly through jasem’s spending store</div></Shell>;
}
